#!/bin/bash
# Get tags
# curl -L -s 'https://registry.hub.docker.com/v2/repositories/ceph/daemon/tags?page_size=1024'|jq '."results"[]["name"]'

CEPH_IMAGE_TAG=ceph/daemon:latest-pacific
CEPH_ENTRYPOINT=demo
S3_IMAGE_TAG=ceph/s3-tests-image:latest
S3_ENTRYPOINT=run-tests
CONF_PATH=/etc/ceph/test.conf
# TODO: for the purposes of GSoC, this should query the IP back from the container, and then use it for s3-tests


CMD=(
 docker run -d -p 8000:8000 --privileged --name ceph-demo 
 -v /etc/modprobe.d:/etc/modprobe.d 
 -v /mnt/ceph:/var/lib/ceph
 -e RGW_FRONTEND_TYPE=beast
 -e DEBUG=verbose
 -e RGW_FRONTEND_PORT=8000
 -e MON_IP=127.0.0.1
 -e CEPH_PUBLIC_NETWORK=0.0.0.0/0
 -e CLUSTER=test
 -e CEPH_DEMO_UID=demo
 -e CEPH_DEMO_ACCESS_KEY=G1EZ5R4K6IJ7XUQKMAED
 -e CEPH_DEMO_SECRET_KEY=cNmUrqpBKjCMzcfqG8fg4Qk07Xkoyau52OmvnSsz
 -e CEPH_DEMO_BUCKET=foobar
 -e SREE_PORT=5001
 -e DATA_TO_SYNC=/etc/modprobe.d
 -e DATA_TO_SYNC_BUCKET=github
 -e OSD_COUNT=2 
 ${CEPH_IMAGE_TAG}
 ${CEPH_ENTRYPOINT}
)

# this might bail out the first time
"${CMD[@]}"

docker start ceph-demo

# bootstrap s3-alt user
if [ -f "demo2" ]; then
    log "Demo user already exists with credentials:"
else
    S3_ALT=(docker exec ceph-demo radosgw-admin -c ${CONF_PATH} user create
    --uid="demo2"
    --display-name="Ceph demo user 2"
    --access-key="NOPQRSTUVWXYZABCDEFG"
    --secret-key="nopqrstuvwxyzabcdefghijklmnabcdefghijklm"
    )
    "${S3_ALT[@]}"
fi

# bootstrap s3-tenant
if [ -f "tenant" ]; then
    log "Demo user already exists with credentials:"
else
    S3_TENANT=(docker exec ceph-demo radosgw-admin -c ${CONF_PATH} user create
	--tenant testx
    --uid="9876543210abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    --access-key="HIJKLMNOPQRSTUVWXYZA"
    --secret="opqrstuvwxyzabcdefghijklmnopqrstuvwxyzab"
    --display-name="tenanteduser"
    --email="tenanteduser@example.com")
    "${S3_TENANT[@]}"
fi

# Get container IP (CIP)
CIP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ceph-demo)

# Copy s3tests.conf.SAMPLE configuration to s3tests.conf 
# and set RGW_IP in host of s3tests.conf as CIP
cp s3tests.conf.SAMPLE s3-tests-docker/s3tests.conf
sed -i "s/RGW_IP/$CIP/g" s3-tests-docker/s3tests.conf

# Build s3-tests image
docker build -t ${S3_IMAGE_TAG} ./s3-tests-docker

# s3-tests container  
CMD=(
docker run --link ceph-demo
--name s3-tests
-e S3_HOST="${CIP}"
-e S3_PORT=8000
${S3_IMAGE_TAG}
${S3_ENTRYPOINT}
)

"${CMD[@]}"

# export coverage.xml,coverage.json,coverage_html and nose-output.xml to PWD
S3_CONTAINER_ID=$(docker ps -aqf "name=s3-tests")
docker cp $S3_CONTAINER_ID:/s3-tests/coverage.xml $PWD
docker cp $S3_CONTAINER_ID:/s3-tests/coverage.json $PWD
docker cp $S3_CONTAINER_ID:/s3-tests/coverage_html $PWD
docker cp $S3_CONTAINER_ID:/s3-tests/nose-output.xml $PWD

# clear exited s3-tests container
docker container rm $(docker ps -q -f status=exited && name=s3-tests)